# Pre-commit hooks configuration
# Run the same checks locally that GitHub Actions runs
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        name: ruff-fix
        args: [--fix]
      - id: ruff
        name: ruff-check
      - id: ruff-format
        name: ruff-format
      - id: ruff-format
        name: ruff-format-check
        args: [--check]

  # MyPy - Type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-lxml>=2024.0.0
          - types-xmltodict>=0.13.0
          - types-python-dateutil>=2.8.0
          - pydantic>=2.0.0
          - fastapi>=0.100.0
          - typer>=0.9.0
          - pdfminer.six>=20221105
          - python-docx>=1.1.0
          - uvicorn>=0.20.0
        args: [--config-file=pyproject.toml, src/]
        pass_filenames: false

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements

  # Pytest - Run tests on commit (matches CI)
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
