# Pre-commit hooks configuration
# Run the same checks locally that GitHub Actions runs
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Black - Code formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11

  # MyPy - Type checker (optional, can be slow)
  # Uncomment to enable:
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.0
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports, --no-strict-optional]

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements

  # Pytest - Run tests on commit (optional, can be slow)
  # Uncomment to enable:
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
