# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"  # Current coverage range

  status:
    project:
      default:
        target: 73%  # Current coverage - maintain or improve
        threshold: 3%  # Allow 3% decrease (down to 70%)
        informational: false
    patch:
      default:
        target: 75%  # New code should have 75%+ coverage
        threshold: 5%
        informational: false

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "setup.py"
