[lint]
select = ["E", "F", "W", "I", "UP"]
# Ignore E501 (line too long) - acceptable for regex patterns, field mappings, and long lists
ignore = ["E501"]

# Alternative: only ignore in specific files
# [lint.per-file-ignores]
# "src/eurocv/core/extract/*.py" = ["E501"]
# "src/eurocv/core/map/*.py" = ["E501"]
# "src/eurocv/core/validate/*.py" = ["E501"]
